In [1]:
import pandas as pd

import os

In [7]:
# downloadsディレクトリのパスを設定
downloads_dir = os.path.join(os.getcwd(), "downloads")

def get_year_list(downloads_dir):
    """downloads直下のすべてのサブディレクトリ（年と仮定）のリストを取得"""
    year_list = [d for d in os.listdir(downloads_dir) if os.path.isdir(os.path.join(downloads_dir, d))]
    return year_list

def get_csv_file_list(downloads_dir, year):
    """指定した年のサブディレクトリ内のすべてのCSVファイルのパスをリストに格納"""
    utf8_csv_dir = os.path.join(downloads_dir, year, "csv")
    csv_file_list = [
        os.path.join(utf8_csv_dir, file)
        for file in os.listdir(utf8_csv_dir)
        if file.endswith(".csv")
    ]
    return csv_file_list

# 年のリストを取得
year_list = get_year_list(downloads_dir)
print(year_list)

# 年を手動で選択（例として最初の年を選択）
selected_year = year_list[2]  # 適宜変更可能

# 選択した年のCSVファイルのパスを取得
csv_file_list = get_csv_file_list(downloads_dir, selected_year)

# 確認のためリストを出力
for csv_file in csv_file_list:
    print(csv_file)

['2012', '2016', '2021']
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H3622.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H3623.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H3624.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H3653.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H3724.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H3725.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H3741.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H3831.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H3926.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H3927.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H3928.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H3942.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4027.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4028.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4042.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4128.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4129.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4229.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4230.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4329.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4429.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4530.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4531.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4629.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4630.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4631.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4729.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4730.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4731.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4828.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4829.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4830.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4831.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4839.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4928.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4929.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4930.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4931.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4932.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4933.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4934.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H4939.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5029.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5030.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5031.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5032.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5033.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5034.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5035.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5036.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5039.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5129.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5130.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5131.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5132.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5133.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5134.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5135.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5136.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5137.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5138.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5139.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5229.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5231.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5232.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5233.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5234.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5235.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5236.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5237.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5238.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5239.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5240.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5332.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5333.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5334.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5335.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5336.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5337.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5338.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5339.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5340.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5432.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5433.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5435.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5436.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5437.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5438.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5439.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5440.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5536.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5537.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5538.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5539.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5540.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5541.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5636.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5637.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5638.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5639.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5640.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5641.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5738.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5739.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5740.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5741.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5839.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5840.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5841.csv
d:\Deveropment\e-stat\downloads\2021\csv\tblT001147H5939.csv

In [8]:
df0 = pd.read_csv(csv_file_list[0])
df0

,KEY_CODE,T001147001,T001147002,T001147003,T001147004,T001147005,T001147006,T001147007,T001147008,T001147009,...,T001147037,T001147038,T001147039,T001147040,T001147041,T001147042,T001147043,T001147044,T001147045,T001147046
0,NaN,Ａ〜Ｓ全産業,Ａ〜Ｒ全産業（Ｓ公務を除く）,Ｃ〜Ｅ第２次産業,Ｃ鉱業，採石業，砂利採取業,Ｄ建設業,Ｅ製造業,Ｆ〜Ｓ第３次産業,Ｆ電気・ガス・熱供給・水道業,Ｇ情報通信業,...,Ｎ生活関連サービス業，娯楽業,Ｏ教育，学習支援業,Ｐ医療，福祉,Ｑ複合サービス事業,Ｒサービス業（他に分類されないもの）,Ｓ公務（他に分類されるものを除く）,男-Ａ〜Ｓ全産業,女-Ａ〜Ｓ全産業,男-Ａ〜Ｒ全産業（Ｓ公務を除く）,女-Ａ〜Ｒ全産業（Ｓ公務を除く）
1,362257283.0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,4,1,4,1
2,362257353.0,5,4,1,0,1,0,4,0,0,...,0,0,3,0,0,177,187,24,23,11
3,362257381.0,10,10,2,0,0,2,8,0,0,...,2,0,0,0,4,0,9,16,9,16
4,362257382.0,8,6,4,0,0,4,4,0,0,...,0,8,0,0,0,0,7,15,4,10
5,362257451.0,15,14,5,0,0,5,10,0,0,...,0,0,4,0,0,0,10,20,10,16
6,362257452.0,24,20,7,0,1,6,16,0,0,...,2,24,0,8,1,1,45,46,34,32
7,362257453.0,1,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,4,1,4
8,362257564.0,1,1,0,0,0,0,1,0,0,...,0,0,21,0,0,0,5,16,5,16
9,362257571.0,1,1,1,0,0,1,0,0,0,...,0,0,0,0,0,0,4,0,4,0
10,362257583.0,8,7,0,0,0,0,8,0,0,...,0,0,0,0,0,0,42,17,33,16
11,362257593.0,5,5,2,0,0,2,3,0,0,...,3,0,0,0,0,0,13,4,13,4
12,362257691.0,1,1,1,0,0,1,0,0,0,...,0,0,0,0,0,0,5,0,5,0
13,362257692.0,8,7,4,0,1,3,4,1,0,...,0,0,0,0,0,1,17,7,16,7

In [9]:
df1 = pd.read_csv(csv_file_list[0])
df1

,KEY_CODE,T001146001,T001146002,T001146003,T001146004,T001146005,T001146006,T001146007,T001146008,T001146009,...,T001146037,T001146038,T001146039,T001146040,T001146041,T001146042,T001146043,T001146044,T001146045,T001146046
0,NaN,Ａ〜Ｓ全産業,Ａ〜Ｒ全産業（Ｓ公務を除く）,Ｃ〜Ｅ第２次産業,Ｃ鉱業，採石業，砂利採取業,Ｄ建設業,Ｅ製造業,Ｆ〜Ｓ第３次産業,Ｆ電気・ガス・熱供給・水道業,Ｇ情報通信業,...,Ｎ生活関連サービス業，娯楽業,Ｏ教育，学習支援業,Ｐ医療，福祉,Ｑ複合サービス事業,Ｒサービス業（他に分類されないもの）,Ｓ公務（他に分類されるものを除く）,男-Ａ〜Ｓ全産業,女-Ａ〜Ｓ全産業,男-Ａ〜Ｒ全産業（Ｓ公務を除く）,女-Ａ〜Ｒ全産業（Ｓ公務を除く）
1,36225728.0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,4,1,4,1
2,36225735.0,5,4,1,0,1,0,4,0,0,...,0,0,3,0,0,177,187,24,23,11
3,36225738.0,18,16,6,0,0,6,12,0,0,...,2,8,0,0,4,0,16,31,13,26
4,36225745.0,40,35,12,0,1,11,27,0,0,...,2,24,4,8,1,1,56,70,45,52
5,36225756.0,1,1,0,0,0,0,1,0,0,...,0,0,21,0,0,0,5,16,5,16
6,36225757.0,1,1,1,0,0,1,0,0,0,...,0,0,0,0,0,0,4,0,4,0
7,36225758.0,8,7,0,0,0,0,8,0,0,...,0,0,0,0,0,0,42,17,33,16
8,36225759.0,5,5,2,0,0,2,3,0,0,...,3,0,0,0,0,0,13,4,13,4
9,36225769.0,9,8,5,0,1,4,4,1,0,...,0,0,0,0,0,1,22,7,21,7